theme = "zed_onedark"

# mouse=true

[editor]
line-number = "relative"
mouse = true
cursorline = true          # 光标所在行高亮
cursorcolumn = false       # 光标所在列高亮
bufferline = "always"
completion-trigger-len = 1
auto-format = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = [
  "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
C-s = ":w"
# C-A-a=":format"
"esc" = ["collapse_selection", ":w"]

[keys.insert]
C-s = ":w"
"esc" = ["normal_mode", ":w"]
# C-S-a=":format"

[keys.select]
C-s = ":w"
# C-S-a=":format"
"esc" = ["collapse_selection", "normal_mode", ":w"]

# "esc" = ["collapse_selection", "normal_mode", ":w"]

# [keys.insert]
# "esc" = ["normal_mode", ":w"]


[keys.normal."A-m"]
"A-1" = [
  "extend_to_line_bounds",
  ":pipe sed -E 's/^(#{1,} )?/# /'",
  "collapse_selection",
]
"A-2" = [
  "extend_to_line_bounds",
  ":pipe sed -E 's/^(#{1,} )?/## /'",
  "collapse_selection",
]
"A-3" = [
  "extend_to_line_bounds",
  ":pipe sed -E 's/^(#{1,} )?/### /'",
  "collapse_selection",
]
"A-4" = [
  "extend_to_line_bounds",
  ":pipe sed -E 's/^(#{1,} )?/#### /'",
  "collapse_selection",
]
"A-5" = [
  "extend_to_line_bounds",
  ":pipe sed -E 's/^(#{1,} )?/##### /'",
  "collapse_selection",
]
"A-6" = [
  "extend_to_line_bounds",
  ":pipe sed -E 's/^(#{1,} )?/###### /'",
  "collapse_selection",
]
"]" = ["extend_to_line_bounds", ":pipe sed -E 's/^#/##/'", "collapse_selection"]
"[" = ["extend_to_line_bounds", ":pipe sed -E 's/^##/#/'", "collapse_selection"]
o = [
  "split_selection_on_newline",
  "goto_first_nonwhitespace",
  ":insert-output printf '1. '",
  "rotate_selections_backward",
  'keep_primary_selection',
  "collapse_selection",
  "goto_line_end",
]
q = [
  "split_selection_on_newline",
  "goto_first_nonwhitespace",
  ":insert-output printf '> '",
  "rotate_selections_backward",
  'keep_primary_selection',
  "collapse_selection",
  "goto_line_end",
]
u = [
  "split_selection_on_newline",
  "goto_first_nonwhitespace",
  ":insert-output printf -- '- '",
  "rotate_selections_backward",
  'keep_primary_selection',
  "collapse_selection",
  "goto_line_end",
]
t = [
  "split_selection_on_newline",
  "goto_first_nonwhitespace",
  ":insert-output printf -- '- [ ] '",
  "rotate_selections_backward",
  'keep_primary_selection',
  "collapse_selection",
  "goto_line_end",
]

[keys.insert."A-m"]
"A-1" = [
  "extend_to_line_bounds",
  ":pipe sed -E 's/^(#{1,} )?/# /'",
  "collapse_selection",
  "insert_at_line_end",
]
"A-2" = [
  "extend_to_line_bounds",
  ":pipe sed -E 's/^(#{1,} )?/## /'",
  "collapse_selection",
  "insert_at_line_end",
]
"A-3" = [
  "extend_to_line_bounds",
  ":pipe sed -E 's/^(#{1,} )?/### /'",
  "collapse_selection",
  "insert_at_line_end",
]
"A-4" = [
  "extend_to_line_bounds",
  ":pipe sed -E 's/^(#{1,} )?/#### /'",
  "collapse_selection",
  "insert_at_line_end",
]
"A-5" = [
  "extend_to_line_bounds",
  ":pipe sed -E 's/^(#{1,} )?/##### /'",
  "collapse_selection",
  "insert_at_line_end",
]
"A-6" = [
  "extend_to_line_bounds",
  ":pipe sed -E 's/^(#{1,} )?/###### /'",
  "collapse_selection",
  "insert_at_line_end",
]
"]" = [
  "extend_to_line_bounds",
  ":pipe sed -E 's/^#/##/'",
  "collapse_selection",
  "insert_at_line_end",
]
"[" = [
  "extend_to_line_bounds",
  ":pipe sed -E 's/^##/#/'",
  "collapse_selection",
  "insert_at_line_end",
]
c = [
  ":insert-output echo '```'",
  ":insert-output echo '```'",
  "collapse_selection",
  "insert_at_line_end",
]
i = [
  "collapse_selection",
  ":insert-output printf '**'",
  "flip_selections",
  "move_char_right",
  "insert_mode",
]
b = [
  "collapse_selection",
  ":insert-output printf '****'",
  "flip_selections",
  "move_char_right",
  "move_char_right",
  "collapse_selection",
  "insert_mode",
]
s = [
  "collapse_selection",
  ":insert-output printf '~~~~'",
  "flip_selections",
  "move_char_right",
  "move_char_right",
  "collapse_selection",
  "insert_mode",
]
k = [
  "collapse_selection",
  ":insert-output printf '<kbd></kbd>'",
  "flip_selections",
  "move_char_right",
  "move_char_right",
  "move_char_right",
  "move_char_right",
  "move_char_right",
  "collapse_selection",
  "insert_mode",
]
"`" = [
  "collapse_selection",
  ":insert-output printf '``'",
  "flip_selections",
  "move_char_right",
  "insert_mode",
]
h = [
  "collapse_selection",
  ":insert-output printf '[]()'",
  "flip_selections",
  "move_char_right",
  "insert_mode",
]
l = [
  "collapse_selection",
  ":insert-output printf '[[]]'",
  "flip_selections",
  "move_char_right",
  "move_char_right",
  "collapse_selection",
  "completion",
  "insert_mode",
]
j = [
  "collapse_selection",
  ":insert-output printf '![](/images/)'",
  "flip_selections",
  "collapse_selection",
  "move_char_right",
  "move_char_right",
  "collapse_selection",
  "insert_mode",
]
o = [
  "goto_first_nonwhitespace",
  ":insert-output printf -- '1. '",
  "collapse_selection",
  "insert_at_line_end",
]
q = [
  "goto_first_nonwhitespace",
  ":insert-output printf -- '> '",
  "collapse_selection",
  "insert_at_line_end",
]
u = [
  "goto_first_nonwhitespace",
  ":insert-output printf -- '- '",
  "collapse_selection",
  "insert_at_line_end",
]
t = [
  "goto_first_nonwhitespace",
  ":insert-output printf -- '- [ ] '",
  "collapse_selection",
  "insert_at_line_end",
]
