[[language]]
name = "markdown"
soft-wrap.enable = true

[[language]]
name = "toml"

[[language]]
name = "javascript"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "typescript"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "lua"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "    " }
formatter = { command = "clang-format", args = [
  "-style=file:/home/dangerise/.config/clang-format/.clang-format",
] }

[language-server.rust-analyzer.config]
completion.autoimport.enable = false
